# Sentiment Analysis {#sentiments}

```{r}
dataDir <- "Proj2Data"
```


```{r}
currTknsByMonth <- read.csv(paste0(dataDir, "/CoinTknsMonthly.csv"))
CommTkns <- read.csv(paste0(dataDir, "/CommTkns.csv"))
```


## Data Shaping

To group comments and their sentiments by `Coin` we have to first assign this identifier to the tokens via their associated `comm_id`.

```{r}
currTkns <- CommTkns %>%
  inner_join(currTknsByMonth[,c("Coin","Month","comm_id")], by = "comm_id")
```

### `get_sentiments()`

```{r}
nrc<- get_sentiments("nrc")
```

`r kbl(head(nrc))`

```{r}
currSntmntTkns <- currTkns %>%
  inner_join(nrc)

sntmntByMonth <-  currSntmntTkns %>%
  group_by(Month, Coin) %>%
  count(sentiment) %>%
  ungroup()
```

```{r}
ggplot(sntmntByMonth, aes(x = Month, y = n, group = sentiment, color = sentiment)) +
  geom_line() +
  facet_wrap(~Coin)
```
```{r}
pBTC <- Quandl('BITFINEX/BTCUSD')
pETH <- Quandl('BITFINEX/ETHUSD')
pLTC <- Quandl('BITFINEX/LTCUSD')
pXRP <- Quandl('BITFINEX/XRPUSD')
```

```{r}
pBTC["Coin"] <- "BTC"
pETH["Coin"] <- "ETH"
pLTC["Coin"] <- "LTC"
pXRP["Coin"] <- "XRP"

PricesByCoin <- rbind(pBTC, pETH, pLTC, pXRP)
```

